### PR TITLE
Update Migrations

### PR DESCRIPTION
**Pull request by Nikhilchudasama**

### CODE REVIEW

**Comment by harimayco** [comment]
Hi Nikhilchudasama Thanks for the PR,
but I think we don't need BigInteger for sort and depth field (integer is more than enough). let me know what you think.

**Comment by Nikhilchudasama** [comment]
hi harimayco
Laravel6 removed integer in migration and feature version will be it remove
so i it.

Thank for my commit accept.

Your faithful
Nikhil

**Comment by Nikhilchudasama** [comment]
sorry for integer remove in laravel6.
Because i always used biginterger in migration if may be length increase
then it will not create problem.

Your faithful
Nikhil

**Comment by harimayco** [comment]
laravel replaces integer to biginteger just for incremental value only. they don't remove integer as data type.
for other field that doesn't need big number like sorting and depth field we can keep using integer

**Pull request merged**
